# Generated by Django 4.2.21 on 2025-05-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumnireview_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnireview',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
