# Generated by Django 4.2.21 on 2025-05-25 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_rename_teacher_history_alumnireview_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacontent',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], max_length=5),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
