# Generated by Django 4.2.21 on 2025-06-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mediacontent_options_mediacontent_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='achievements',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='history',
            name='name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='position',
        ),
        migrations.AlterField(
            model_name='history',
            name='photo',
            field=models.ImageField(upload_to='history/'),
        ),
    ]
